[package]
name = "expand-derive"
version = "0.1.0"
authors = ["Daniel Rehren <daniel.rehren.a@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
arr_macro = "0.1"
